[project]
name = "jellybench_py"
version = "0.1.0"
description = "Hardware Acceleration Benchmark - python Client for Jellyfin Hardware Survey"
authors = [
    {name="BotBlake", email="B0TBlake@protonmail.com"},
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests (>=2.31.0)",
    "py-cpuinfo (>=9.0.0)",
    "progressbar2 (>=4.5.0)",
    "wmi; sys_platform == 'win32'",
]

[dependency-groups]
dev = [
    "ipython (>=9.0.0)",
    "ruff (>=0.14, <0.15)",
    "pre-commit (>=4.0.0)",
    "pytest>=8.4.1",
]

[project.scripts]
jellybench = 'jellybench_py.core:main'

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
