name: Lint Jellybench

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        py_version: ['3.9', '3.10', '3.11', '3.12']

    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.py_version }}

      - name: Lint with ruff on python ${{ matrix.py_version }}
        run: uv run ruff check src/jellybench_py

